### USE CASE 1
GET http://localhost:8081/registrationevents/latest

### USE CASE 7
PATCH http://localhost:8081/registrationevents/updatestatus/1?processed=true

### USER CASE 3 - GET
GET  http://localhost:8081/registrationevents/get/1

### USE CASE 4
GET  http://localhost:8081/registrationevents/by-student-id/2


### USE CASE 6
GET  http://localhost:8081/registrations/6


### USE CASE 5

POST http://localhost:8081/student/registration/
Content-Type: application/json

{
  "courseId": 1,
  "priority": 1,
  "requested": true
}
