### USE CASE 1
GET http://localhost:8081/registrationevents/latest

### USE CASE 7
PATCH http://localhost:8081/registrationevents/updatestatus/1?processed=true

### USER CASE 3 - GET
GET  http://localhost:8081/registrationevents/get/1

### USE CASE 4
GET  http://localhost:8081/registrationevents/by-student-id/2


### USE CASE 6
GET  http://localhost:8081/registrations/3


### USE CASE 5

POST http://localhost:8081/student/registration/
Content-Type: application/json

{
  "courseId": 1,
  "priority": 1,
  "requested": true
}

###

POST http://localhost:8081/admin/process/2


###
POST http://localhost:8081/registrationevents/create
Content-Type: application/json

{
  "name": "New event for registration",
  "startDateTime": "2022-12-21 19:49:59",
  "endDateTime": "2023-12-23 19:49:59"
}



### CREATE COURSE OFFERING

POST http://localhost:8081/courseoffering/create
Content-Type: application/json

{
  "faculty_id": 1,
  "block_id": 2,
  "course_id": 1,
  "totalSeat": 55
}


### CREATE BLOCK

POST http://localhost:8081/academicBlocks/create
Content-Type: application/json

{
  "name": "December",
  "semester": "Fall",
  "startWeek": 3,
  "endWeek": 4,
  "year": 2022,
  "month": 12,
  "day": 1
}

### CREATE REGISTRATION GROUP

POST http://localhost:8081/admin/registrationgroup/create
Content-Type: application/json

{
  "title": "FPP"
}

### ADD STUDENTS TO GROUP

PUT http://localhost:8081/admin/registrationgroup/add/students
Content-Type: application/json

{
  "groupId": 3,
  "students": [
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11
  ]
}

### Adding registration group block

PUT http://localhost:8081/admin/registrationgroup/add/block
Content-Type: application/json

{
  "groupId": 3,
  "blockIds": [1,3,4]
}

### Student registration request

POST http://localhost:8081/student/registration/
Content-Type: application/json

{
  "student_id": 3,
  "event_id": 8,
  "group_id": 3,
  "request": [
    {
      "course_id": 1,
      "priority": 1,
      "requested": true
    },
    {
      "course_id": 2,
      "priority": 2,
      "requested": true
    }
  ]
}


